### ISSUE TITLE
Incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)

### ISSUE THREAD

**Issue by warmwaffles** [intridea/oauth2#155]
So google in all of its infinite wisdom decides to send back an infinity symbol in the error messages.

```
/Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/error.rb:21:in `join': incompatible character encodings: UTF-8 and ASCII-8BIT (Encoding::CompatibilityError)
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/error.rb:21:in `initialize'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:109:in `new'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/client.rb:109:in `request'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/access_token.rb:107:in `request'
	from /Users/warmwaffles/.rbenv/versions/2.0.0-p247/lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/access_token.rb:114:in `get'
```
**Response in google before fix:**

```json
{
   "error":{
      "errors":[
         {
            "domain":"global",
            "reason":"invalidParameter",
            "message":"Invalid value '0'. Values must be within the range: [1, \xE2\x88\x9E)",
            "locationType":"parameter",
            "location":"start-index"
         }
      ],
      "code":400,
      "message":"Invalid value '0'. Values must be within the range: [1, \xE2\x88\x9E)"
   }
}
```

ruby structure

```ruby
{
  "errors"=>[
    {
      "domain"=>"global", 
      "reason"=>"invalidParameter", 
      "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)", 
      "locationType"=>"parameter", 
      "location"=>"start-index"
    }
  ], 
  "code"=>400, 
  "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)"
}
```

originates from `lib/ruby/gems/2.0.0/gems/oauth2-0.9.2/lib/oauth2/error.rb:21:in 'initialize'`

Proposed solution:

```diff
module OAuth2
  class Error < StandardError
    attr_reader :response, :code, :description

    # standard error values include:
    # :invalid_request, :invalid_client, :invalid_token, :invalid_grant, :unsupported_grant_type, :invalid_scope
    def initialize(response)
      response.error = self
      @response = response

      message = []

      if response.parsed.is_a?(Hash)
        @code = response.parsed['error']
        @description = response.parsed['error_description']
        message << "#{@code}: #{@description}"
      end

-      message << response.body
+      message << response.body.force_encoding("UTF-8")

      super(message.join("\n"))
    end
  end
end
```

**Response from google after fix:**

```json
{
   "error":{
      "errors":[
         {
            "domain":"global",
            "reason":"invalidParameter",
            "message":"Invalid value '0'. Values must be within the range: [1, ∞)",
            "locationType":"parameter",
            "location":"start-index"
         }
      ],
      "code":400,
      "message":"Invalid value '0'. Values must be within the range: [1, ∞)"
   }
}
```

ruby structure:

```ruby
{
  "errors" => [
    {
      "domain"=>"global",
      "reason"=>"invalidParameter",
      "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)",
      "locationType"=>"parameter",
      "location"=>"start-index"
    }
  ], 
  "code"=>400, 
  "message"=>"Invalid value '0'. Values must be within the range: [1, ∞)"
}
```

I tried to be as thorough as possible. I don't know what this means in regards to breaking anything. I just ran this test with `bundle open`

**Comment by jhmoore** [comment]
We needed this fix as well and it worked for us.

**Comment by synth** [comment]
I'm still encountering an issue here. I get error: 

      "\xC3" from ASCII-8BIT to UTF-8

Found a fix in this branch:
https://github.com/fjg/oauth2/commit/e4b4dfd90536eaf7c94c2afbab2aec9fc2780dea
